name: Deploy to Firebase

on:
  push:
    branches:
      - main  # or the branch you are deploying from

jobs:
  deploy:
    runs-on: ubuntu-latest  # or other OS if needed

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Choose your preferred node version

    # Install project dependencies
    - name: Install dependencies
      run: npm install

    # Install Firebase CLI globally
    - name: Install Firebase CLI
      run: npm install -g firebase-tools  # Ensures firebase tools are installed in CI

    # Authenticate Firebase using the Firebase token (make sure this is set in GitHub secrets)
    - name: Firebase Authentication
      run: firebase use --add

    # Deploy to Firebase
    - name: Deploy to Firebase
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
